PowerBiRazorApp/Models/AzureAdSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PowerBiRazorApp.Models
{
    public class AzureAdSettings
    {
        public string Instance { get; set; }
        public string TenantId { get; set; }
        public string ClientId { get; set; }
        public string CallbackPath { get; set; }
        public string TokenType { get; set; }
    }
}

PowerBiRazorApp/Models/ErrorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace PowerBiRazorApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public int Code { get; set; }
        public string Message { get; set; }
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}

PowerBiRazorApp/Models/OAuthResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace PowerBiRazorApp.Models
{
    public class OAuthResult
    {
        [JsonProperty("token_type")]
        public string TokenType { get; set; }
        [JsonProperty("scope")]
        public string Scope { get; set; }
        [JsonProperty("expires_in")]
        public int ExpiresIn { get; set; }
        [JsonProperty("ext_expires_in")]
        public int ExtExpiresIn { get; set; }
        [JsonProperty("expires_on")]
        public int ExpiresOn { get; set; }
        [JsonProperty("not_before")]
        public int NotBefore { get; set; }
        [JsonProperty("resource")]
        public Uri Resource { get; set; }
        [JsonProperty("access_token")]
        public string AccessToken { get; set; }
        [JsonProperty("refresh_token")]
        public string RefreshToken { get; set; }
    }
}

PowerBiRazorApp/Models/PowerBiSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PowerBiRazorApp.Models
{
    public class PowerBiSettings
    {
        public string MainAddress { get; set; }
        public string ResourceAddress { get; set; }
        public string MasterUser { get; set; }
        public string MasterKey { get; set; }
        public string GroupId { get; set; }
    }
}

PowerBiRazorApp/Models/ReportEmbedConfig.cs
using System;

namespace PowerBiRazorApp.Models
{
    /// <summary>
    /// An object of the necessary details for the client to embed the report
    /// </summary>
    public class ReportEmbedConfig
    {
        /// <summary>
        /// The Power BI report ID
        /// </summary>
        public Guid ReportID { get; set; }

        /// <summary>
        /// Name of report
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Access token associated with report
        /// </summary>
        public string AccessToken { get; set; }

        /// <summary>
        /// Embed Url for report
        /// </summary>
        public string EmbedUrl { get; set; }
    }
}

PowerBiRazorApp/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PowerBiRazorApp.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

PowerBiRazorApp/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PowerBiRazorApp.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

PowerBiRazorApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PowerBiRazorApp.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PowerBiRazorApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PowerBiRazorApp.DataAccess;
using Microsoft.PowerBI.Api.V2.Models;

namespace PowerBiRazorApp.Pages
{
    public class IndexModel : PageModel
    {
        public List<Report> AvailableReports { get; private set; }
        private readonly ReportRepository _reportRepo;

        public IndexModel(ReportRepository reportRepo)
        {
            _reportRepo = reportRepo;
        }

        public async Task OnGetAsync()
        {
            var reports = await _reportRepo.GetAvailableReportsAsync();
            AvailableReports = reports.ToList();
        }

    }

}

PowerBiRazorApp/Pages/Report.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PowerBiRazorApp.DataAccess;
using PowerBiRazorApp.Models;

namespace PowerBiRazorApp.Pages
{
    public class ReportModel : PageModel
    {
        public ReportEmbedConfig ReportDetail { get; private set; }

        private readonly ReportRepository _reportRepo;

        /// <param name="reportRepo"></param>
        public ReportModel(ReportRepository reportRepo)
        {
            _reportRepo = reportRepo;
        }

        /// <returns></returns>
        public async Task OnGetAsync(Guid reportID, string name, string role)
        {
            if(name == null && role == null)
                ReportDetail = await _reportRepo.GetReportForIdAsync(reportID);
            else
                ReportDetail = await _reportRepo.GetReportForIdAsync(reportID, name, role);
        }
    }
}

PowerBiRazorApp/Pages/RowLevelSecurityTester.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PowerBiRazorApp.Pages
{
    public class RowLevelSecurityTesterModel : PageModel
    {
        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public string Role { get; set; }

        [BindProperty]
        public Guid ReportID { get; set; }

        public RowLevelSecurityTesterModel()
        {
        }

        public void OnGet(Guid reportID)
        {
            ReportID = reportID;
        }

        /// <summary>
        /// Sets the row level security permissions towards the report
        /// </summary>
        /// <returns></returns>
        public IActionResult OnPostSetReportRLS()
        {
            return RedirectToPage("Report", new { reportID = ReportID, name = Name, role = Role });
        }

    }
}

PowerBiRazorApp/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

PowerBiRazorApp/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PowerBiRazorApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="list-group">
    <h1>Available Reports</h1>

    @*<ul>
        @foreach (var report in @Model.AvailableReports)
        {
            <li><a asp-page="/RowLevelSecurityTester" asp-route-reportID="@report.Id">@report.Name <span class="sr-only">(current)</span></a></li>
        }
    </ul>*@

</div>

PowerBiRazorApp/Pages/Report.cshtml
@page "{reportID}/{Name?}/{Role?}"
@model ReportModel

<h2>@Model.ReportDetail.Name</h2>
<div id="desktopReport" class="embedded-report"> </div>

@section Styles{
    <link rel="stylesheet" href="~/custom/reportStyle.css" />
}

@section Scripts{
    <script src="~/lib/powerbi/powerbi.min.js"></script>
    <script type="text/javascript">
        var models = window['powerbi-client'].models;

        var config = {
            type: "report",
            id: '@Model.ReportDetail.ReportID',
            accessToken: '@Model.ReportDetail.AccessToken',
            embedUrl: '@Model.ReportDetail.EmbedUrl',
            tokenType: 1,
            settings: {
            }
        };

        var reportContainer = document.getElementById("desktopReport");
        powerbi.embed(reportContainer, config);
    </script>
}

PowerBiRazorApp/Pages/RowLevelSecurityTester.cshtml
@page "{reportID}"
@model RowLevelSecurityTesterModel

<div class="list-group">
    <form method="POST" asp-page-handler="SetReportRLS">
        <h1>Input Row Level Security Information (Optional)</h1>
        Name <input asp-for="Name" />
        Role <input asp-for="Role" />
        <input class="btn btn-success" style="margin: 10px" type="submit" value="Set Row Level Security" />
    </form>
</div>

PowerBiRazorApp/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dealers Insights</title>

    <link rel="shortcut icon" href="~/images/volvo/Volvo_iron_mark_RGB_40x40px.png" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/fonts/css/all.css" />
    <link rel="stylesheet" href="~/css/jquery.mCustomScrollbar.min.css" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/sidebar-themes.css" />
    @RenderSection("Styles", false)
</head>
<body>
    <div class="page-wrapper ice-theme sidebar-bg bg1 toggled">
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-item sidebar-brand">
                    <a asp-page="/Index">Dealer Insights</a>
                </div>
            </div>
            <div class="sidebar-item sidebar-header d-flex flex-nowrap">
                <div class="user-pic">
                    <img class="img-responsive img-rounded" src="~/images/general/user.jpg" alt="User picture">
                </div>
                <div class="user-info">
                    <span class="user-name">
                        @*@name <strong>@lastName</strong>*@
                    </span>
                </div>
            </div>
            <div class=" sidebar-item sidebar-menu">
                <ul>
                    <li class="header-menu">
                        <span>General</span>
                    </li>
                    <li class="sidebar-dropdown">
                        <a asp-page="/Index">
                            <i class="fa fa-tachometer-alt"></i>
                            <span class="menu-text">Dashboards</span>
                        </a>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="far fa-money-bill-alt"></i>
                            <span class="menu-text">Financial Services</span>
                        </a>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-truck" aria-hidden="true"></i>
                            <span class="menu-text">Parts</span>
                        </a>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            <span class="menu-text">Sales</span>
                        </a>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-wrench" aria-hidden="true"></i>
                            <span class="menu-text">Services</span>
                        </a>
                    </li>
                    @*<li class="sidebar-dropdown">
                            <a asp-area="" asp-controller="Home" asp-action="Privacy">
                                <i class="fa fa-wrench" aria-hidden="true"></i>
                                <span class="menu-text">Privacy</span>
                            </a>
                        </li>*@
                </ul>
            </div>
        </nav>
        <main class="page-content pt-2">
            <div class="form-group col-md-1" style="margin-bottom: 0px;">
                <a id="toggle-sidebar" class="btn btn-dark" href="#">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </a>
            </div>
            <div id="overlay" class="overlay"></div>
            <div class="container-fluid p-5">
                <partial name="_CookieConsentPartial" />
                <div class="row">
                    <div class="form-group col-md-12">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </main>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>